const actionsType = {
  START_DRAG_LEFT: "START_LEFT_DRAG",
  START_DRAG_RIGHT: "START_RIGHT_DRAG",
  MOVE_SLIDER: "MOVE_SLIDER",
  MOVE_SLIDER_END: "MOVE_SLIDER_END",
  END_DRAG_LEFT: "END_DRAG_LEFT",
  END_DRAG_RIGHT: "END_DRAG_RIGHT",
  PLAY_VIDEO: "PLAY_VIDEO",
  PAUSE_VIDEO: "PAUSE_VIDEO",
  SET_CUT_VIDEO: "SET_CUT_VIDEO",
};

export default actionsType;
